---
- name: Installing UFW
  apt: name=ufw state=present update_cache=yes

- name: Configuring UFW rules
  ufw:
    from_ip: '{{ item.from_ip|default(omit) }}'
    to_ip: '{{ item.to_ip|default(omit) }}'
    to_port: '{{ item.to_port|default(omit) }}'
    proto: '{{ item.proto|default(omit) }}'
    rule: '{{ item.rule|default("allow") }}'
  with_items: '{{ firewall_rules + firewall_rules_custom }}'

- name: Starting UFW
  ufw: state=enabled

- name: Configuring UFW policies
  ufw:
    direction: '{{ item.direction|default(omit) }}'
    policy: '{{ item.policy|default(omit) }}'
  with_items: '{{ firewall_policies }}'

