---
- name: Operating system dependencies
  apt: name={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - git
    - python-pip
    - python-virtualenv
    - dialog
    - libaugeas0
    - ca-certificates

- name: Python cryptography module
  pip: name=cryptography

- name: Letsencrypt Python client
  git:
    dest: /opt/certbot
    clone: yes
    update: yes
    repo: https://github.com/certbot/certbot
    force: yes
    version: '{{letsencrypt_certbot_version}}'

- set_fact:
    letsencrypt_certbot_renew:
      - "{{ letsencrypt_force_renew|ternary(' --renew-by-default ', ' --keep-until-expiring ')}}"

- name: Stopping Services
  service: name="{{item}}" state=stopped
  with_items: "{{ letsencrypt_pause_services }}"
  ignore_errors: yes
  register: _services_stopped

- include_tasks: 'obtain.yml'
  with_items: '{{letsencrypt_domains_groups}}'

- name: Starting paused Services
  service: name="{{item.item}}" state=started
  when: (item.state is defined and item.state == "stopped")
  with_items: "{{ _services_stopped.results|default([]) }}"

#- fail: msg="Error signing the certificate"
#  when: not letsencrypt_test and not _signing_successful and not _signing_skipped
